[tool.poetry]
name = "ctboj"
version = "0.1.0"
description = ""
authors = ["pms <apark0907@ajou.ac.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
